# Generated by Django 5.2.8 on 2025-12-31 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('plinko', 'Plinko'), ('slots', 'Slots'), ('wheel', 'Wheel'), ('cards', 'Cards'), ('mining', 'Mining')], max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('maintenance_message', models.TextField(default='This game is temporarily under maintenance. Please try again later.', help_text='Message shown to users when game is disabled')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Game Control',
                'verbose_name_plural': 'Game Controls',
                'db_table': 'game_controls',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('plinko', 'Plinko'), ('slots', 'Slots'), ('wheel', 'Wheel'), ('cards', 'Cards'), ('mining', 'Mining')], db_index=True, max_length=20)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss')], max_length=10)),
                ('multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('points_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('game_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='users.user')),
            ],
            options={
                'db_table': 'game_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='game_sessio_user_id_d02a40_idx'), models.Index(fields=['game_type', '-created_at'], name='game_sessio_game_ty_27586e_idx')],
            },
        ),
    ]
