# Generated by Django 5.2.8 on 2026-01-01 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameControl',
        ),
    ]
